name: "PokéDex deployer"

on: 
  push:
    branches: [ main ]
      

env:
  PROJECT_PATH: Pokemon/Pokemon/Pokemon.csproj
  


jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-dotnet@v1
        with:
         dotnet-version: '6.0.x'
         include-prerelease: true
      - run: dotnet restore ${{ env.PROJECT_PATH }}
      - run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore
      - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
